baseURL = "https://blog.a-1.dev/"
languageCode = "ja"
title = "A1 Blog"
theme = "hugo_theme_robust"
preserveTaxonomyNames = true
paginate = 10
googleAnalytics = "UA-136833263-1"
disqusShortname="a1-blog"
hasCJKLanguage = true
# Build robots.txt file
enableRobotsTXT = true
enableEmoji = true
hrefTargetBlank = true
timeout = 30000

[params]
  description = ""
  dateformat = "Jan 2, 2006" # Optional
  # Fonts settings.
    googlefonts = "https://fonts.googleapis.com/css?family=Lobster|Lato:400,700" # Optional, Include google fonts.
  fontfamily = "Lato,YuGothic,'Hiragino Kaku Gothic Pro',Meiryo,sans-serif" # Optional, Override body font family.
  #logofontfamily = "Lobster, cursive" # Optional, Override logo font.
  OgpApiEndpoint = "https://blog.a-1.dev/.netlify/functions/ogp?url="
  #OgpApiEndpoint = "http://localhost:9000/ogp?url="

[params.author]
  thumbnail = "images/a1.png"
  name = "A1"
  description = "<p>プログラマです</p><p>Vim派/JIS配列派/タケノコ派</p>"
  #facebook = "https://www.facebook.com/daisuke.tsuji.735"
  twitter = "https://twitter.com/eichisanden"
  github = "https://github.com/eichisanden"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
page = [ "HTML", "AMP" ]
