[build]
publish = "public"
command = "hugo --gc --minify --enableGitInfo"

[context.production.environment]
HUGO_VERSION = "0.54.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[headers]]
for = "/*"
[headers.values]
Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"

[[redirects]]
from = "https://curator-badger-35454.netlify.com/*"
to = "https://gyoza.beer/:splat"
status = 301
force = true
