[build]
publish = "public"
command = "npm run build && hugo --gc --minify --enableGitInfo"
functions="./functions"

[context.production.environment]
HUGO_VERSION = "0.55.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[headers]]
for = "/*"
[headers.values]
Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"

[[redirects]]
from = "https://gyoza.beer/*"
to = "https://blog.a-1.dev/:splat"
status = 301
force = true

[[redirects]]
from = "https://angry-euclid-67959a.netlify.com/*"
to = "https://blog.a-1.dev/:splat"
status = 301
force = true
